language: c++
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
install:
- export CXX=g++-5
- sudo ci/install_biicode.sh
- bii setup:cpp
script: make
deploy:
  provider: biicode
  user: Towerism
  password:
    secure: F1+oRQdLQVa7ee1JeJfIz1JagGrsuKt4HjitvComokYFx5vfYJcHIikUOCDjNCAWpJ8s7sfx5b3JI675khPETAW8dFy0cBpCZkUjyBUoJF6zxrIYvBYhWVKugv3lpbYIJ82SRsZSP7uw18WJjOuEbUCaavg6Kb/RgM/dY2JN5XLeUXg8A481PGinaPCAdYZBZhIf9pfNrR1B9m04SnJGUmI1f/uPvUzG6J9e1McbTp/Ml9Ggenp2gHxlA08A6LeeB6ItI906iEVQ7WNvDghUtEK0N8QbKqM/ctBKItQF2gTsCPKCY1Q++6hVtkKW08sElQPECbIi9hsXH7SHTSquEQ8OFqH5i1PODMTskrTL8ncyBMY5i4iqegPKBkhqo9LboDUJA2Jw9eRVXygeHOXsRY+XyWA9wM4uFULsu3ocOoskJ5RD01R6pxPGRsMPKCJactcQ4M1+H5UfVzRirFbUf1kAbIlw2fNwB0kQqptBmFeHsEl+6tzyDntZU8cxKr4bxvO776OBskCw7WqkSalSShEalVDVzI4a41UFzLDQv5VMpUu9dgr3p3taXqKPEHoQfOuvgcC6DuVasPDDiXv2sSN6LWSnWS/8YQZuaWnHas/85buQTgQCtQ+WRJK48o7f6s8TSDDmh9ZZMB6z1b6iLLDGPTD3KT5hesbTSxE+LLQ=
  on:
    repo: Towerism/FrackDB
    branch: develop
