language: cpp
addons:
  apt:
    sources:
      - george-edison55-precise-backports # CMake 3.2
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake
      - gcc-5
      - g++-5

env:
  - TEST_SUITE=unit
  - TEST_SUITE=integration
  - TEST_SUITE=coverage

before_install:
  - ci/install_lcov.sh
  - gem install coveralls-lcov
  - export PATH=$PWD/usr/bin/:$PATH
  - ln -s $(which gcov-5) usr/bin/gcov

script: ci/script.sh

after_success: ci/upload_coverage.sh

notifications:
  email: false
