language: c++

env:
  global:
    - BII_USER=Towerism
    - secure: YYu3sqLvFyHZRShRYtDNNCB+jdohFRD2p+/GY3HfWwJkenEXYE5oTngWVY3lH0SfazVwKpqa6UogURHa5mmABFDlNUPNVJ53XcMXTbD1x30VP1PMbSGWbLw3u6Xz+Wi8Mg4HS+d7hegz1pph18/k1ZFEzsMOKxyG5gU7v/BkLK2ez15Y37WZ4x/OJTQpXRjjddeWYTZbidC72BLlRMEyc/AzT4OldugeB1FzQYpFgVpMo/iQMyw8BO7AU37Nzxig6XuZ3vuuFYXfuyWISAxmwKxX+3Wuka6Orah4VU3WEnFCI9pooMEpkfzeEBwRcPCgXrgCVTD1UlaDgAUcMkPH93TAmqtd0I3mxxp00/KCDX/lL7a0p8a0szha/U4QeZVjBXz5RDvr801EGQCh/I1r7AuijssXo9iRXlxPJUPcgQkrC1Ny+BZJ5AEOt8IMXUHCCnGb6G1JXQJ2jScexG8LKoRj5VC8v7oIKKtFO/AP52eu6AgOn6Y1pJO0Wd1XzwaBvj669HJlzoUw9VQzkUEbTqAQ0cEvrr28RliRihXqoT0xDN0qC6b7mm97XB8OvXyhRemLkUaojymiQyZLLW1rPKRkpwSrFs4DAUnp015QnkRJKzp4Kq4nIzVvPrkFcs3AmqmSgu/FbLGUok6SeotIvqPRViNdtm0T77Ta21q0oro=
    - secure: L/xpX3hRMAhP5UqL7DvcmqwjfckxYD1ieC33CHlwh5hhxP34FXScgK2xI/34A5degBHgd35fuB2T29k1piEPHSoG09gFYhemmJnO60mDMSwIrPZ8mJP82/KkJZDv5xYUFN7aiejYl9mXGMl5M1LlgdmqzQ+MakEiVU5zDc7ujhnm5rwztGOVQ4Quf5KKRWYNqYRBoiSlbqxDnHx1bHPKh7IvxxQR+qIpng96H8g72l+vjbC3FEBP1gBpzqFA0N/ojVhTpXqa7x+CP38+bNQrY6L2Rnk4r+omE1T4xjwEVnnWNegF3C+1jIglxZPUEDknAkUVCmw+Rbu6vdElzhny04oOwfT/3v/wPjK9jnG0UwqImOxMyU+K8aBm9OFiJV7hwhOD//7ipRwOEoeqtergZw3ak3abSWzJvT+wolWQ1/eFDT8Yh1eRuve5MAtFB3dZ74tbcHvCxdoIORAjTiyndhDzE4xQp8r8eI5p5RSlxoLvanXJqnmTx7ruObtd8+uOqSrm4IfPzx/BHEtSS5QZ80g+lZyiV+tWglqOp8Msgrr92GwdaLzZKWCkoRsqLwWsw4lxX4EPRSoZDMc6fPxdITRhpDr36MO0eYIP87dD9qmh6cwnvLVryUr+SU1X4mWjPKViDZCXpvaepNaxHf/q5EUXvFrJCN9vzUy6qOTXvIM=

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - g++-5
      - libboost-all-dev
  coverity_scan:
    project:
      name: "Towerism/FrackDB"
      description: "Another database management system"
    notification_email: martin.frackerjr@gmail.com
    build_command: make
    branch_pattern: coverity-scan

install:
  - bundle install
  - sudo ci/install_lcov.sh
  - sudo ci/fix_symlinks.sh
  - sudo ci/install_biicode.sh
  - bii setup:cpp

script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make coverage; fi

after_success:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then bii user "$BII_USER" -p "$BII_PASSWORD"; fi
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then bii --publish; fi  
- if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then coveralls-lcov bii/build/coverage/coverage.info.cleaned; fi
