language: c++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - g++-5
      - libboost-all-dev

install:
  - export CXX=g++-5
  - wget http://launchpadlibrarian.net/188120513/lcov_1.11-3_all.deb
  - sudo dpkg -i lcov_1.11-3_all.deb
  - rm lcov_1.11-3_all.deb
  - sudo rm -f /usr/bin/gcov
  - sudo ln /usr/bin/gcov-5 /usr/bin/gcov
  - sudo ci/install_biicode.sh
  - gem install coveralls-lcov
  - bii setup:cpp

script: make coverage

after_success:
  - bii user "$BII_USER" -p "$BII_PASSWORD"
  - bii publish --remote
  - coveralls-lcov bii/build/coverage/coverage.info.cleaned

env:
  global:
    - BII_USER=Towerism
    # BII_PASSWORD > travis encrypt BII_PASSWORD=xxxxx --add
    - secure: YYu3sqLvFyHZRShRYtDNNCB+jdohFRD2p+/GY3HfWwJkenEXYE5oTngWVY3lH0SfazVwKpqa6UogURHa5mmABFDlNUPNVJ53XcMXTbD1x30VP1PMbSGWbLw3u6Xz+Wi8Mg4HS+d7hegz1pph18/k1ZFEzsMOKxyG5gU7v/BkLK2ez15Y37WZ4x/OJTQpXRjjddeWYTZbidC72BLlRMEyc/AzT4OldugeB1FzQYpFgVpMo/iQMyw8BO7AU37Nzxig6XuZ3vuuFYXfuyWISAxmwKxX+3Wuka6Orah4VU3WEnFCI9pooMEpkfzeEBwRcPCgXrgCVTD1UlaDgAUcMkPH93TAmqtd0I3mxxp00/KCDX/lL7a0p8a0szha/U4QeZVjBXz5RDvr801EGQCh/I1r7AuijssXo9iRXlxPJUPcgQkrC1Ny+BZJ5AEOt8IMXUHCCnGb6G1JXQJ2jScexG8LKoRj5VC8v7oIKKtFO/AP52eu6AgOn6Y1pJO0Wd1XzwaBvj669HJlzoUw9VQzkUEbTqAQ0cEvrr28RliRihXqoT0xDN0qC6b7mm97XB8OvXyhRemLkUaojymiQyZLLW1rPKRkpwSrFs4DAUnp015QnkRJKzp4Kq4nIzVvPrkFcs3AmqmSgu/FbLGUok6SeotIvqPRViNdtm0T77Ta21q0oro=
